"""websites table

Revision ID: 0fdf6a86fed3
Revises: 131b5624e2c4
Create Date: 2022-06-03 20:43:58.223680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdf6a86fed3'
down_revision = '131b5624e2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False, unique=True),
    sa.Column('link', sa.String(), nullable=False, unique=True),
    sa.Column('phone_number', sa.String(), nullable=False, unique=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('websites')
    # ### end Alembic commands ###
