"""added link a website title differences

Revision ID: 131b5624e2c4
Revises: 2441dba6841e
Create Date: 2022-05-30 21:43:54.273462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131b5624e2c4'
down_revision = '2441dba6841e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo', sa.Column('website_link', sa.String(), nullable=False))
    op.add_column('promo', sa.Column('website_title', sa.String(), nullable=False))
    op.drop_column('promo', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('promo', 'website_title')
    op.drop_column('promo', 'website_link')
    # ### end Alembic commands ###
