"""changed prices

Revision ID: 2441dba6841e
Revises: a2391c4c1cc7
Create Date: 2022-05-29 17:40:11.801009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2441dba6841e'
down_revision = 'a2391c4c1cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promo', 'new_price', type_=sa.String())
    op.alter_column('promo', 'old_price', type_=sa.String())
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promo', 'new_price', type_=sa.Float())
    op.alter_column('promo', 'old_price', type_=sa.Float())
    pass
    # ### end Alembic commands ###
