"""promo table

Revision ID: a2391c4c1cc7
Revises: 6a08e3f504f1
Create Date: 2022-05-29 17:37:59.797156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2391c4c1cc7'
down_revision = '6a08e3f504f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cathegory', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promo')
    # ### end Alembic commands ###
